export const myVeryLogo = [
  {
    id: 1,
    image: '/icons/green-logo.svg',
    label: 'MyVeryOwnWay',
    alt: 'green-logo',
  },
  {
    id: 2,
    image: '/icons/pink-logo.svg',
    label: 'MyVeryOwnWay',
    alt: 'pink-logo',
  },
  {
    id: 3,
    image: '/icons/purple-logo.svg',
    label: 'MyVeryOwnWay',
    alt: 'purple',
  },
  {
    id: 4,
    image: '/icons/skyLogo.svg',
    label: 'MyVeryOwnWay',
    alt: 'sky-logo',
  },
  {
    id: 5,
    image: '/icons/orange-logo.svg',
    label: 'MyVeryOwnWay',
    alt: 'orange-logo',
  },
  {
    id: 6,
    image: '/icons/green-logo.svg',
    label: 'MyVeryOwnWay',
    alt: 'green-logo',
  },
  {
    id: 7,
    image: '/icons/pink-logo.svg',
    label: 'MyVeryOwnWay',
    alt: 'pink-logo',
  },
  {
    id: 8,
    image: '/icons/purple-logo.svg',
    label: 'MyVeryOwnWay',
    alt: 'purple',
  },
  {
    id: 9,
    image: '/icons/skyLogo.svg',
    label: 'MyVeryOwnWay',
    alt: 'sky-logo',
  },
  {
    id: 10,
    image: '/icons/orange-logo.svg',
    label: 'MyVeryOwnWay',
    alt: 'orange-logo',
  },
  {
    id: 11,
    image: '/icons/green-logo.svg',
    label: 'MyVeryOwnWay',
    alt: 'green-logo',
  },
  {
    id: 12,
    image: '/icons/pink-logo.svg',
    label: 'MyVeryOwnWay',
    alt: 'pink-logo',
  },
  {
    id: 13,
    image: '/icons/purple-logo.svg',
    label: 'MyVeryOwnWay',
    alt: 'purple',
  },
  {
    id: 14,
    image: '/icons/skyLogo.svg',
    label: 'MyVeryOwnWay',
    alt: 'sky-logo',
  },
  {
    id: 15,
    image: '/icons/orange-logo.svg',
    label: 'MyVeryOwnWay',
    alt: 'orange-logo',
  },
  {
    id: 16,
    image: '/icons/purple-logo.svg',
    label: 'MyVeryOwnWay',
    alt: 'purple',
  },
  {
    id: 17,
    image: '/icons/skyLogo.svg',
    label: 'MyVeryOwnWay',
    alt: 'sky-logo',
  },
  {
    id: 18,
    image: '/icons/orange-logo.svg',
    label: 'MyVeryOwnWay',
    alt: 'orange-logo',
  },
];
